Notification service's implementation (Sms, Email)
DiyorMarket/CheckDrive.Api pull request #15
Opened 2024-10-05 17:45 UTC by aXayitov

2024-10-06 11:13 UTC, Ramadan1011 requested changes

2024-10-06 11:13 UTC, Ramadan1011 commented on CheckDrive.Api/CheckDrive.Infrastructure/Sms/Factories/SmsMetadataFactory.cs
> +internal class SmsMetadataFactory : ISmsMetadataFactory
seperate with an empty line

2024-10-07 08:54 UTC, FirdavsAX commented on CheckDrive.Api/CheckDrive.Infrastructure/Email/Templates/EmailConfirmationTemplate.cshtml
You have english word in line 450 . Garage is will be Garaj because you use Garaj other paths

2024-10-07 08:54 UTC, FirdavsAX commented on CheckDrive.Api/CheckDrive.Infrastructure/Sms/Factories/ISmsMetadataFactory.cs
> +internal interface ISmsMetadataFactory
how can  you use this interface with internal keyword in other layers. It was be public in my opinion

2024-10-07 08:54 UTC, FirdavsAX commented on CheckDrive.Api/CheckDrive.Infrastructure/Sms/SmsService.cs
> +        { SmsType.ForgotPassword, "PasswordResetTemplate.txt" }
Why enum types and template names is not same there like in top one?

2024-10-15 20:32 UTC, Mirazyzz requested changes
Please, address review comments mentioned by @FirdavsAX

2025-01-12 13:49 UTC, closed without merging