233 added email and Sms services
DiyorMarket/CheckDrive.Api pull request #237
Opened 2024-09-26 11:06 UTC by aXayitov

2024-09-26 11:53 UTC, Boburm1rzo approved these changes

2024-09-27 10:18 UTC, FirdavsAX requested changes

2024-09-27 10:18 UTC, FirdavsAX commented on CheckDrive.Api/CheckDrive.Api/Extensions/DependencyInjection.cs
> +            }
you can Use there null coalescing operators : ?? throw new InvalidOpertaionException to code reduction, but its not mandatory

2024-09-27 10:18 UTC, FirdavsAX commented on CheckDrive.Api/CheckDrive.Infrastructure/Email/EmailService.cs
> +       { EmailType.DebtNotification, "DebtNotificationTemplate.cshtml" }
You have not a  DebtNotification template in this project . You can remove this Element

2024-09-27 10:18 UTC, FirdavsAX commented on CheckDrive.Api/CheckDrive.Infrastructure/Email/Factories/EmailMetadataFactory.cs
> +        { EmailType.DebtNotification, "Debt warning" }
You have not DebtNotification template view. You can remove that, its not necessary

2024-09-27 10:18 UTC, FirdavsAX commented on CheckDrive.Api/CheckDrive.Infrastructure/Email/Factories/IEmailMetadataFactory.cs
> +    List<string>? cc = null);
There code is not readeble, please use put each parameter to separate row.

2024-09-27 10:18 UTC, FirdavsAX commented on CheckDrive.Api/CheckDrive.Infrastructure/Models/EmailType.cs
> +        DebtNotification
you have not DebtNotification template, please remove it in enum

2024-09-28 10:06 UTC, FirdavsAX approved these changes

2024-09-28 15:49 UTC, Mirazyzz approved these changes
Looks good!

2024-09-28 15:49 UTC, merged