Validation_For_Create_DTOs
DiyorMarket/CheckDrive.Api pull request #6
Opened 2024-10-05 09:59 UTC by SharifovDeveloper

2024-10-05 15:39 UTC, Mirazyzz requested changes
Where are the validations for the properties defined in **ReviewBaseDto**?

2024-10-05 15:39 UTC, Mirazyzz commented on CheckDrive.Api/CheckDrive.Api/CheckDrive.Api.csproj
> +    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
it should be in application layer

2024-10-05 15:39 UTC, Mirazyzz commented on CheckDrive.Api/CheckDrive.Api/Extensions/DependencyInjection.cs
Validators should be configured in Application Layer

2024-10-05 15:39 UTC, Mirazyzz commented on CheckDrive.Api/CheckDrive.Api/Program.cs
> +using FluentValidation.AspNetCore;
where is this used?

2024-10-05 15:39 UTC, Mirazyzz commented on CheckDrive.Api/CheckDrive.Api/Program.cs
> +builder.Host.UseSerilog();
redundant space

2024-10-05 15:39 UTC, Mirazyzz commented on CheckDrive.Api/CheckDrive.Application/DTOs/DispatcherReview/CreateDispatcherReviewDto.cs
> +    int DriverId,
CheckPointid should be enough, because CheckPoint.DoctorReview already contains DriverId we can take from there.

2024-10-05 15:39 UTC, Mirazyzz commented on CheckDrive.Api/CheckDrive.Application/Validators/CreateDispatcherReviewDtoValidator.cs
> +public class CreateDispatcherReviewDtoValidator : AbstractValidator<CreateDispatcherReviewDto>
where is namespace for this class?

2024-10-05 15:39 UTC, Mirazyzz commented on CheckDrive.Api/CheckDrive.Application/Validators/CreateDoctorReviewDtoValidator.cs
> +            .GreaterThan(0).WithMessage("Haydovchini tanlashingiz shart.");
do we need to check for DoctorId?

2024-10-05 15:39 UTC, Mirazyzz commented on CheckDrive.Api/CheckDrive.Infrastructure/CheckDrive.Infrastructure.csproj
> +    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
does his layer need this package?

2024-10-05 15:39 UTC, Mirazyzz commented on CheckDrive.Api/CheckDrive.TestDataCreator/CheckDrive.TestDataCreator.csproj
> +    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
does his layer need this package?

2024-10-05 15:39 UTC, Mirazyzz commented on CheckDrive.Api/Tests/CheckDrive.Tests.Api/CheckDrive.Tests.Api.csproj
> +    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
does his layer need this package?

2024-10-05 15:39 UTC, Mirazyzz commented on CheckDrive.Api/Tests/CheckDrive.Tests.Unit/CheckDrive.Tests.Unit.csproj
> +    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
does his layer need this package?

2024-10-16 08:05 UTC, aXayitov approved these changes

2024-10-16 08:05 UTC, aXayitov commented on CheckDrive.Api/CheckDrive.Application/Validators/CreateDispatcherReviewDtoValidator.cs
> +public class CreateDispatcherReviewDtoValidator : AbstractValidator<CreateDispatcherReviewDto>
there must be a space.

2024-10-16 08:05 UTC, aXayitov commented on CheckDrive.Api/CheckDrive.Application/Validators/CreateDoctorReviewDtoValidator.cs
> +public class CreateDoctorReviewDtoValidator : AbstractValidator<CreateDoctorReviewDto>
there must be a space here as well

2024-10-16 08:05 UTC, aXayitov commented on CheckDrive.Api/CheckDrive.Application/Validators/CreateMechanicAcceptanceReviewDtoValidator.cs
> +public class CreateMechanicAcceptanceReviewDtoValidator : AbstractValidator<CreateMechanicAcceptanceReviewDto>
!

2024-10-17 21:16 UTC, Mirazyzz commented
change target branch from master to integration

2024-11-11 09:19 UTC, closed without merging